language: node_js
node_js: stable
cache:
  directories:
  - node_modules
jobs:
  include:
    - stage: "test"
      name: "Run E2E Test"
      script: npm run cypress:test
    - stage: deploy
      if: branch = master
      name: "Deploy to GAE"
      deploy:
        provider: gae
        keyfile: client-secret.json
        project: thesis-281217
        skip_cleanup: true
        local_dir: build
