language: node_js
node_js: stable
cache:
  directories:
  - node_modules
branches:
  only:
  - master
jobs:
  include:
    - stage: "test"
      name: "Run E2E Test"
      script: npm run cypress:test
    - stage: deploy
      name: "Deploy to GAE"
      script: skip
      deploy:
        provider: gae
        keyfile: client-secret.json
        project: thesis-281217
        skip_cleanup: true
        local_dir: build
        on:
          branch: master
