language: node_js
node_js: stable
script:
- npm run build
true:
  branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_2fd045226a67_key -iv $encrypted_2fd045226a67_iv
  -in client-secret.json.enc -out client-secret.json -d
deploy:
  provider: gae
  keyfile: client-secret.json.enc
  project: thesis-281217

