language: node_js
node_js: stable
cache:
  directories:
  - node_modules
script:
  - npm run build
true:
  branch: master
deploy:
  provider: gae
  keyfile: client-secret.json
  project: thesis-281217
  skip_cleanup: true
  local_dir: build
stages:
  - name: deploy
    # require the branch name to be master (note for PRs this is the base branch name)
    if: branch = master
